select * from
(
select
	'1R' rtype,
	ELM_ID_DO_IC,
	CLASSE_R,
	NOME_LOGICO_R,
	NOME_DO_IC_ORIGEM_R,
	NOME_DO_IC_DESTNO_R,
	ID_DO_IC_R,
	TIPO_IC_R,
	NIVEL_1_R,
	NIVEL_2_R,
	NIVEL_3_R,
	NOME_DO_PRODUTO_R,
	CLASSE_PAI_R,
	CLASSE_FILHO_R,
	ELM_NOME_DO_IC,
	ELM_chave_base,
	ELM_tipo_ic,
	ELM_Nivel_1,
	ELM_Nivel_2,
	ELM_Nivel_3,
	ELM_NOME_DO_PRODUTO,
	ELM_NOME_LOGICO,
	ELM_SIGLA,
	ELM_REGIAO,
	ELM_SITE,
	ELM_ANDAR,
	ELM_COMPLEMENTO,
	ELM_STATUS,
	ELM_MOTIVO_DO_STATUS,
	UPPER(ELM_NUMERO_DE_SERIE) AS ELM_NUMERO_DE_SERIE,
	ELM_BP,
	ELM_TIPO_DE_AQUISICAO,
	RR
from
(
select 'Filho' RR,
    R.CLASSE CLASSE_R,
	R.NOME_LOGICO NOME_LOGICO_R,
	R.NOME_DO_IC_ORIGEM NOME_DO_IC_ORIGEM_R,
	R.NOME_DO_IC_DESTNO NOME_DO_IC_DESTNO_R,
	R.ID_DO_IC ID_DO_IC_R,
	R.TIPO_IC TIPO_IC_R,
	R.Nivel_1 NIVEL_1_R,
	R.Nivel_2 NIVEL_2_R,
	R.Nivel_3 NIVEL_3_R,
	R.NOME_DO_PRODUTO NOME_DO_PRODUTO_R,
	R.CLASSE_PAI CLASSE_PAI_R,
	R.CLASSE_FILHO CLASSE_FILHO_R,
    E.ID_DO_IC ELM_ID_DO_IC,
    E.NOME_LOGICO ELM_NOME_LOGICO,
    E.NOME_DO_PRODUTO ELM_NOME_DO_PRODUTO,
    E.NIVEL_1 ELM_NIVEL_1,
    E.NIVEL_2 ELM_NIVEL_2,
    E.NIVEL_3 ELM_NIVEL_3,
    E.chave_base ELM_chave_base,
    E.SIGLA ELM_SIGLA,
    E.REGIAO ELM_REGIAO,
    E.SITE ELM_SITE,
    E.ANDAR ELM_ANDAR,
    E.COMPLEMENTO ELM_COMPLEMENTO,
    E.STATUS ELM_STATUS,
    E.MOTIVO_DO_STATUS ELM_MOTIVO_DO_STATUS,
    E.NUMERO_DE_SERIE ELM_NUMERO_DE_SERIE,
    E.BP ELM_BP,
    E.TIPO_DE_AQUISICAO ELM_TIPO_DE_AQUISICAO,
    E.TIPO_IC ELM_TIPO_IC,
    E.NOME_DO_IC ELM_NOME_DO_IC
  from bdgc_relationship R, bdgc_element E
where R.c400130900 = E.chave_base
UNION all
select 'Pai' RR,
    R.CLASSE CLASSE_R,
	R.NOME_LOGICO NOME_LOGICO_R,
	R.NOME_DO_IC_ORIGEM NOME_DO_IC_ORIGEM_R,
	R.NOME_DO_IC_DESTNO NOME_DO_IC_DESTNO_R,
	R.ID_DO_IC ID_DO_IC_R,
	R.tipo_ic TIPO_IC_R,
	R.Nivel_1 NIVEL_1_R,
	R.Nivel_2 NIVEL_2_R,
	R.Nivel_3 NIVEL_3_R,
	R.NOME_DO_PRODUTO NOME_DO_PRODUTO_R,
	R.CLASSE_PAI CLASSE_PAI_R,
	R.CLASSE_FILHO CLASSE_FILHO_R,
    e.ID_DO_IC ELM_ID_DO_IC,
    E.NOME_LOGICO elm_NOME_LOGICO,
    E.NOME_DO_PRODUTO elm_NOME_DO_PRODUTO,
    E.NIVEL_1 ELM_NIVEL_1,
    E.NIVEL_2 ELM_NIVEL_2,
    E.NIVEL_3 ELM_NIVEL_3,
    E.chave_base ELM_chave_base,
    E.SIGLA ELM_SIGLA,
    E.REGIAO ELM_REGIAO,
    E.SITE ELM_SITE,
    E.ANDAR ELM_ANDAR,
    E.COMPLEMENTO ELM_COMPLEMENTO,
    E.STATUS ELM_STATUS,
    E.MOTIVO_DO_STATUS ELM_MOTIVO_DO_STATUS,
    E.NUMERO_DE_SERIE ELM_NUMERO_DE_SERIE,
    E.BP ELM_BP,
    E.TIPO_DE_AQUISICAO ELM_TIPO_DE_AQUISICAO,
    E.TIPO_IC ELM_TIPO_IC,
    E.NOME_DO_IC ELM_NOME_DO_IC
  from bdgc_relationship R, bdgc_element E
where R.c400131000 = E.chave_base

)  zohar

UNION ALL

select
	'2P' rtype,
	E.id_do_ic ID_DO_IC,
	P.NOME_COMPLETO AA,
	P.PAPEL BB,
	' ' CC,
	' ' DD,
	' ' EE,
	' ' FF,
	' ' GG,
	' ' HH,
	' ' II,
	' ' JJ,
	' ' KK,
	' ' LL,
	E.NOME_DO_IC ELM_NOME_DO_IC,
	E.chave_base ELM_chave_base,
	E.TIPO_IC ELM_TIPO_IC,
	E.NIVEL_1 ELM_NIVEL_1,
    E.NIVEL_2 ELM_NIVEL_2,
    E.NIVEL_3 ELM_NIVEL_3,
	E.NOME_DO_PRODUTO elm_NOME_DO_PRODUTO,
	E.NOME_LOGICO ELM_NOME_LOGICO,
    E.SIGLA ELM_SIGLA,
    E.REGIAO ELM_REGIAO,
    E.SITE ELM_SITE,
    E.ANDAR ELM_ANDAR,
    E.COMPLEMENTO ELM_COMPLEMENTO,
    E.STATUS ELM_STATUS,
    E.MOTIVO_DO_STATUS ELM_MOTIVO_DO_STATUS,
    E.NUMERO_DE_SERIE ELM_NUMERO_DE_SERIE,
    E.BP ELM_BP,
    E.TIPO_DE_AQUISICAO ELM_TIPO_DE_AQUISICAO,
	' ' RR

from
	bdgc_people P,
	bdgc_element E
where
	E.chave_base = P.CHAVE_PEOPLE 
) J   
where ELM_ID_DO_IC <> ID_DO_IC_R 
and NIVEL_2_R <> 'COMPONENTE'  
and ELM_Nivel_2 <> 'COMPUTADOR PESSOAL' AND NIVEL_2_R <> 'COMPUTADOR PESSOAL'
and ELM_Nivel_2 <> 'EQUIPAMENTO PERIFERICO' AND NIVEL_2_R <> 'EQUIPAMENTO PERIFERICO'
and ELM_Nivel_2 <> 'VIDEO/IMAGEM' AND NIVEL_2_R <> 'VIDEO/IMAGEM'